### ISSUE TITLE
Fix updating

### ISSUE THREAD

**Issue by ChandlerSwift** [ChandlerSwift/duluth-bus-tracker#8]
After some amount of updates, the auto updating stops working. I don't think it's a recursion depth limit, but that's not impossible. The Flask server does keep running though (so the screen updates), and it'll update manually when on-screen buttons are clicked.

**Comment by ChandlerSwift** [comment]
The console shows this error on the server:
```
[2020-01-03 04:44:46,279] ERROR in app: Exception on /api/get-upcoming-departures [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 694, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.local/share/virtualenvs/duluth-transit-1QTzD5Rl/lib/python3.5/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 32, in get_upcoming_departures
    return jsonify(api_consumer.get_upcoming_departures(*RELEVANT_BUSES))
  File "/home/pi/duluth-transit/api_consumer/__init__.py", line 43, in get_upcoming_departures
    with urllib.request.urlopen(UPCOMING_STOP_TIMES_DATA_URL) as url:
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1282, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

**Comment by ChandlerSwift** [comment]
Full error log: [errors.log](https://github.com/ChandlerSwift/duluth-bus-tracker/files/4024054/errors.log)

**Comment by ChandlerSwift** [comment]
d926174a44f25c4f024c57f20097ef7ce98aeb38 and b72b5d5694c605cf612ac1352fe45646d02c0e68 may do something to help this.

**Comment by ChandlerSwift** [comment]
Currently an issue with DTA's API, which 404s. 
http://duluthtransit.com/TMGTFSRealTimeWebService/GTFS-RealTime/TrapezeRealTimeFeed.json
